es2/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace es2.Models
{
    public class Customer
    {
        [Required]
        [Display(Name = "Customer#")]
        public int CustID { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Customer Name")]
        public string CustName { get; set; }


        [StringLength(50)]
        [Display(Name = "Email")]
        [EmailAddress]
        public string CustEmail { get; set; }


        [Required]
        [Display(Name = "Plan Name")]
        public int PlanID { get; set; }
    }
}

/*
CREATE TABLE [dbo].[Customers](
	[CustID] [int] IDENTITY(1,1) NOT NULL,
	[CustName] [varchar](50) NULL,
	[CustEmail] [varchar](50) NULL,
	[PlanID] [int] NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[CustID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
 
 */

es2/Controllers/CustomersController.cs
using es2.App_Classes;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Linq;

namespace es2.Controllers
{
    public class CustomersController : Controller
    {

        public ActionResult PrepList(DataTableAjaxPostModel model)
        {

            //var x = new WebApiWrapper<CustomersViewModel>(CommonCode.UrlCombine(CommonCode.GetAppUrl(), "api", "CustomersApi"));
            //var retVal = await x.JqueryDataTablePost(model);
            //return Json(retVal, JsonRequestBehavior.AllowGet);

            var innerJoin = _DbContext.Customers.Join(_DbContext.Plans
                    , pe => pe.PlanID, pl => pl.PlanID
                    , (pe, pl) => new CustomersViewModel
                    {
                        CustEmail = pe.CustEmail,
                        CustID = pe.CustID,
                        CustName = pe.CustName,
                        PlanName = pl.PlanName
                    });

            var repo = new ListCustomers();
            return Json(repo.LoadJqueryDataTable(model, innerJoin));
            
        }

        public ActionResult Index()
        {
            ViewData["Title"] = "Home > Customers";
            ViewBag.PreviousAction = "Home";
            ViewBag.PreviousController = "Home";
            ViewBag.CrudAction = "Add";
            return View();

        }

        public ActionResult Add()
        {
            PrepFormControls();
            ViewData["Title"] = "Home > Customers > Adding a customer";
            ViewBag.CrudAction = "Create";
            var plan = new es2.Models.Customer();
            return View("Edit", plan);

        }

        public async Task<ActionResult> Edit(int id)
        {
            PrepFormControls();
            ViewData["Title"] = "Home > Customers > Editing a customer";
            ViewBag.CrudAction = "Update";

            var customer = await GetCustomer(id); // find by primary key

            return View(customer);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(es2.Models.Customer customer, string updateType)
        {
            ViewData["Title"] = "Home > Customers > Editing a customer";

            if (updateType.Equals("Delete"))
            {
                DeleteCustomer(customer);
            }
            else
            {
                if (!ModelState.IsValid) { PrepFormControls(); return View("Edit", customer); }
                UpdateCustomer(customer);
            }
            return RedirectToAction(GetIndexAction());

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(es2.Models.Customer customer)
        {
            ViewData["Title"] = "Home > Customers > Adding a customer";
            if (!ModelState.IsValid) { PrepFormControls(); return View("Edit", customer); }

            AddCustomer(customer);

            return RedirectToAction(GetIndexAction());

        }

        private void PrepFormControls(object previousActionParameters = null)
        {
            ViewBag.PreviousActionParameters = previousActionParameters;
            ViewBag.Plans = GetPlans();

        }

        private string GetIndexAction(string id = null)
        {
            return string.Format("{0}{1}", nameof(Index), id == null ? string.Empty : @"/" + id);

        }

        private class Plans
        {
            public int PlanID { get; set; }
            public string PlanName { get; set; }
        }

        private List<Plans> GetPlans()
        {
            var retVal = new List<Plans>();
            var sql = @"
                SELECT
                  b.PlanID
                , b.PlanName
                FROM
                   [Plans] b
            ";
            using (var rs = new Framework_Code.DataAccess("ES"))
            {
                foreach (System.Data.DataRow row in rs.ExecuteQuery(sql).Rows)
                {
                    retVal.Add(new Plans { PlanID = Convert.ToInt32(row["PlanID"]), PlanName = row["PlanName"].ToString() });
                }
            }

            return retVal;
        }

        // callled from wrapper.RequestHeaderPreparing += AddHeader; 
        private void AddHeader(object sender, WebApiWrapper<es2.Models.Customer>.Args e)
        {
            var username = "abc";
            var password = "123";
            var encoded = System.Convert.ToBase64String(System.Text.Encoding.GetEncoding("ISO-8859-1").GetBytes($"{username} : {password}"));
            e.Client .DefaultRequestHeaders.Add("Authorization", "Basic " + encoded);
        }

        private async Task<es2.Models.Customer> GetCustomer(int custID)
        {
            //var x = new WebApiWrapper<es2.Models.Customer>(CommonCode.UrlCombine(CommonCode.GetAppUrl(), "api", "CustomersApi"));
            //x.RequestHeaderPreparing += AddHeader; 
            //return await x.Get(custID.ToString());

            var sql = @"
                SELECT
                  a.CustID
                , a.CustName
                , a.CustEmail
                , a.PlanID
                FROM
                   [Customers] a
                WHERE
                   a.CustID = @CustID 
            ";
            using (var rs = new Framework_Code.DataAccess("ES"))
            {
                rs.SetParameterValue("CustID", custID);
                var row = rs.ExecuteQuery(sql).Rows[0];
                return new es2.Models.Customer
                {
                    PlanID = Convert.ToInt32(row["PlanID"]),
                    CustName = row["CustName"].ToString(),
                    CustEmail = row["CustEmail"].ToString(),
                    CustID = Convert.ToInt32(row["CustID"])
                };
            }
        }

        private void AddCustomer(es2.Models.Customer customer)
        {
            var sql =
        @"

            INSERT INTO [Customers]
            (
     
                 [CustName]
	            ,[CustEmail]
	            ,[PlanID]

            ) VALUES (
     
                 @CustName
	            ,@CustEmail
	            ,@PlanID

            )

            ";

            using (var rs = new Framework_Code.DataAccess("ES"))
            {

                rs.SetParameterValue("CustName", customer.CustName);
                rs.SetParameterValue("CustEmail", customer.CustEmail);
                rs.SetParameterValue("PlanID", customer.PlanID);

                rs.ExecuteNonQuery(sql);
            }

        }

        private void DeleteCustomer(es2.Models.Customer customer)
        {
            var sql =
        @"
                DELETE FROM [Customers] WHERE CustID = @CustID 
                ";

            using (var rs = new Framework_Code.DataAccess("ES"))
            {
                rs.SetParameterValue("CustID", customer.CustID);
                rs.ExecuteNonQuery(sql);
            }

        }

        private void UpdateCustomer(es2.Models.Customer customer)
        {
            var sql =
        @"
            UPDATE [Customers] SET
                 [CustName] = @CustName
	            ,[CustEmail] = @CustEmail
	            ,[PlanID] = @PlanID
            WHERE
                [CustID] = @CustID
            ";

            using (var rs = new Framework_Code.DataAccess("ES"))
            {

                rs.SetParameterValue("CustName", customer.CustName);
                rs.SetParameterValue("CustEmail", customer.CustEmail);
                rs.SetParameterValue("PlanID", customer.PlanID);
                rs.SetParameterValue("CustID", customer.CustID);

                rs.ExecuteNonQuery(sql);

            }

        }

        private readonly ApplicationDbContext _DbContext;
        public CustomersController() { _DbContext = new ApplicationDbContext(); } // ctor
        protected override void Dispose(bool disposing) { _DbContext.Dispose(); }


    } // class
}

es2/Views/Customers/Edit.cshtml
@model es2.Models.Customer

@section Styles {
    @*    This section is defined in _Layout.cshtml as @RenderSection("Styles", required: false) above the <head> tag.*@
    <link href="~/Content/jquery-bpopup.css" rel="stylesheet" />
    <style type="text/css">
        .navbar-inverse {
            background-color: whitesmoke;
        }
    </style>

}

<div id="information" class="popupContent" style="display:none">
    <a class="popupClose" href="#">x</a>
    Update and Delete operations are for the purpose of demonstration only.
    <br />
    They do not affect the data.
</div>
<div style="background-color:whitesmoke">
    <h5>
        <b>
            @ViewData["Title"]
            @if (ViewBag.CrudAction != "Create")
            {
                <a href="#" title="Click here for more information" onclick="popupOpen();">
                    <span class="glyphicon glyphicon-info-sign" style="color:blue;" aria-hidden="true"></span>
                </a>
            }
        </b>
</h5> @*ViewData["Title"] is set in the controller*@
</div>

@using (Html.BeginForm((string)ViewBag.CrudAction, (string)ViewContext.RouteData.Values["controller"]))
{

    @Html.AntiForgeryToken() @*This is needed if you are using [ValidateAntiForgeryToken] on Action methods*@

    @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })
    <div class="container container-fluid">

        <div class="form-group">
            @Html.HiddenFor(m => m.CustID)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustName, htmlAttributes: new { @class = "control-label col-md-2", @dir = "rtl" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustEmail, htmlAttributes: new { @class = "control-label col-md-2", @dir = "rtl" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlanID, htmlAttributes: new { @class = "control-label col-md-2", @dir = "rtl" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.PlanID, new SelectList(ViewBag.Plans, "PlanID", "PlanName"), "Please pick one...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PlanID, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>



    @*------------------------------------------------------No user serviceable code below this line--------------------------------------------------*@

    @Html.Partial("_Edit");

    @section Scripts {
        @*    This section is defined in _Layout.cshtml as @RenderSection("Scripts", required: false) above the </body> tag.*@
        <script src="~/Scripts/jquery.bpopup.min.js"></script>
        <script type="text/javascript">
            function popupOpen() {
                $('#information').bPopup({
                    closeClass: 'popupClose'
                });
            };
        </script>

    }

}

es2/Views/Customers/Index.cshtml
@section Styles {
    @*    This section is defined in _Layout.cshtml as @RenderSection("Styles", required: false) above the <head> tag.*@
    <link type="text/css" rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link href="~/Content/jquery-bpopup.css" rel="stylesheet" />
}

    <div id="information" class="popupContent" style="display:none">
        <a class="popupClose" href="#">x</a>
        This approach reduces the count of CRUD forms per model to 2 from the default of 4.
        <br/><br/>
        Additonally, templated CRUD forms greatly reduce the time it takes to create and service them while delivering a consistent user experience.
    </div>

<div style="background-color:whitesmoke">
    <h5>
        <b>
            @ViewData["Title"]
            <a href="#" title="Click here for more information" onclick="popupOpen();">
                <span class="glyphicon glyphicon-info-sign" style="color:blue;" aria-hidden="true"></span>
            </a>

        </b>
    </h5> @*ViewData["Title"] is set in the controller*@
</div>

<table class="table table-striped" id="listItems">
    <thead>
        <tr>
            <th>
            </th>
            <th>
                Customer#
            </th>
            <th>
                Customer Name
            </th>
            <th>
                Email
            </th>
            <th>
                Plan Name
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="5">Loading data...</td>
        </tr>
    </tbody>
</table>

@*------------------------------------------------------No user serviceable code below this line--------------------------------------------------*@

@Html.Partial("_List")


@section Scripts {
    @*    This section is defined in _Layout.cshtml as @RenderSection("Scripts", required: false) above the </body> tag.*@

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery.bpopup.min.js"></script>

    <script type="text/javascript">

        function popupOpen() {
            $('#information').bPopup({
                closeClass: 'popupClose'
            });
        };

        $(document).ready(function () {
            $('#listItems').DataTable({
                "proccessing": true,
                "serverSide": true,
                "stateSave": true,
                "ajax": {
                    url: "@Url.Action("PrepList", "Customers")",
                    type: 'POST'
                },
               "columns": [
                   { "data": "EditLink" },
                   { "data": "CustID" },
                   { "data": "CustName" },
                   { "data": "CustEmail" },
                   { "data": "PlanName" }
                ],
                "columnDefs": [
                    { "orderable": false, "targets": 0 } // do not sort col #1 (Edit Link)
                ],
                "order": [[1, "desc"]] // default sort on col #2
            });
        });
    </script>

}